sudo: false
language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
before_script:
  - sudo apt-get upgrade -qq
  - sudo apt-get install -qq mpg123
notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/5b722d32-5e6f-4089-aec1-860ba3c1adee
  email: false
